import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Navbar from './components/Navbar'

import { useEffect, useState } from 'react'
export default function Home() {

  return (
    <div className={styles.container}>
      <Navbar></Navbar>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,100;0,300;0,400;0,500;1,200&display=swap" rel="stylesheet" />

      </Head>
      <div className={styles.first_container}>
        <div className={styles.title_container}>
          <div className={styles.main_title}>Mohamad Khawam</div>
          <div className={styles.sub_title}>With Time Anything is Possible</div>
        </div>
      </div>
      <div className={styles.text_container}>
        <div className={styles.info_container}>
          <div className={styles.title}>Who Am I?</div>
          <div className={styles.paragraph}>I’ve been programming for about 7 years now. Started making C# apps and ended up studying computer science at Rutgers University. My knowledge of Node js allows me to build robust backends for websites and web apps. My background gives me the ability to learn new concepts quickly and deploy them at a professional level. I’ve also had a lot of experience programming in java and python. </div>

        </div>
        <div className={styles.info_container}>
          <div className={styles.title}>Why JavaScript?</div>
          <div className={styles.paragraph}>My introduction to Object-Oriented Programming (OOP) was with Java. I learned how to create objects based on the tasks each component needed to accomplish. One of the most important parts of coding is its readability. Due to the nature of code, readability is crucial to the deployment of applications. OOP gives code a better sense of readability and gives the programmer the ability to locate/fix bugs. Javascript is like a sister language to Java and includes OOP. Making JS and knowledge of JS important to the software industry. Node js is a framework which uses the V8 engine to run native JS in a dekstop environment. It also has a large library of useful tools which help reduce the time it takes to make professional apps.</div>
        </div>
      </div>
      <div className={styles.third_container}></div>
      <div className={styles.text_container}>
        <div className={styles.info_container}>
          <div className={styles.title}>Design</div>
          <div className={styles.paragraph}>Designing projects is hard work, but reducing the problem into its parts helps you take it step by step. Take time to understand the problem that your looking to fix. Develop a plan to tackle it.</div>
        </div>
      </div>
      <div className={styles.fifth_container}></div>
      <div className={styles.text_container}>
        <div className={styles.info_container}>
          <div className={styles.title}>Why did I make this Website?</div>
          <div className={styles.paragraph}>I wanted a way to display what I know. Todays coding interviews focus soly on the idea of speed and not as much on the abilities needed to code. We tend to forget just how much work goes into someones knowledge. Coding doesn't have to be a up hill battle. If you have the skills to be able to research and look up what you do not know. Slowly you can build the knowledge to code at a higher level. This goes for everything in life.
          </div>
        </div>
      </div>



      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>

        </a>
        <a>
          Created With{' '}
          <span className={styles.logo}>
            <Image src="/Nextjs-logo.svg" alt="Next JS Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
