import React from 'react'
import Footer from './components/Footer'
import Navbar from './components/Navbar'
import Head from 'next/head'
import Image from 'next/image'
import styles from "../styles/Projects.module.scss"
function Projects() {
    function linkToAccretion() {
        window.location.href = "https://www.accretionnft.com"
    }
    return (
        <div>
            <Head>
                <title>Projects - Khawam</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
                <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,100;0,300;0,400;0,500;1,200&display=swap" rel="stylesheet" />
            </Head>
            <Navbar active="Projects" />
            <div className={styles.body}>
                <div className={styles.top_padding}></div>
                <div className={styles.first_container}>
                    <div className={styles.text_container}>
                        <div className={styles.title}>
                            Accretion
                        </div>
                        <div className={styles.subtitle}> Accretion is a NFT bot I developed with a friend of mine.</div>
                        <div className={styles.description}>
                            Accretion was one of the bigger projects I had the pleasure of developing. For most, it was really fun getting to develop and designing a working web application. My friend focused on the marketing aspects while I focuses on the creation of the bot. The project stack included Mongo DB, React, Node JS, Express JS, and Electron. I also developed a RSA secure websocket API which allowed the bot have a split frontend and backend functionality. The backend of the app is a separate package that gets downloaded from the accretion server on login. The frontend then executes that package which deploys a websocket which it can commutate through. Our servers will receive data on the users blockchain transactions. Allowing us to keep track on the applications performance in the real world.
                        </div>
                        <div className={styles.button} onClick={linkToAccretion}>Accretion Website</div>
                    </div>
                    <div className={styles.ui_image}>
                        <Image src="/ui_svg_design.svg" alt='Accretion Bot' width={700} height={600} >
                        </Image>
                    </div>

                </div>
            </div>
            <Footer />
        </div>
    )
}

export default Projects