import React from 'react'
import styles from '../styles/resume.module.scss'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from './components/Navbar'
function Resume() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Resume</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
                <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,100;0,300;0,400;0,500;1,200&display=swap" rel="stylesheet" />

            </Head>
            <Navbar active="Resume" />
            <div className={styles.first + ' ' + styles.text_container}>
                <div className={styles.title}>Resume</div>
                <div className={styles.content}>
                    <div className={styles.content_container}>
                        <div className={styles.title_content}>Objective</div>
                        <div className={styles.content_info}>To acquire a form of work to build my skills and to use them to solve problems. Seeking to apply my skills in computer programming, computer hardware, webpage design, and knowledge of complex systems to drive further developments. Looking to leverage my skills to learn and adapt to new systems both fast and effectively. </div>
                    </div>
                    <div className={styles.content_container}>
                        <div className={styles.title_content}>Experience</div>
                        <div className={styles.subtitle}>C-Tech</div>
                        <div className={styles.subtitle}>2019-2021
                        </div>
                        <div className={styles.content_info}>I worked for 2 years part-time as a computer technician at c-tech computers in Rochelle Park, NJ. I learned a lot about computer networks and how computers communicate with each other. The job consisted of fixing any problems that can come up with computers. </div>
                    </div>
                    <div className={styles.content_container}>
                        <div className={styles.subtitle}>Swish</div>
                        <div className={styles.subtitle}>July, 2021-Dec, 2021
                        </div>
                        <div className={styles.content_info}>Development of tools and backend using Node JS. Swish’s main goal is to provide tools for the web. Giving people automated use of their website. Swish is a start-up company looking to change how the web works</div>
                    </div>
                    <div className={styles.content_container}>
                        <div className={styles.title_content}>Education</div>
                        <div className={styles.subtitle}>Hasbrouck Heights High School, Hasbrouck Heights, NJ</div>
                        <div className={styles.subtitle}>2016-2020
                        </div>
                        <div className={styles.content_info}>GPA: 3.9</div>
                        <div className={styles.content_info}>Relevant Classes: Computer Programming, AP Computer Science, AP Biology,                 Intro to CAD</div>
                        <div className={styles.content_info}>Clubs: Medical Club, Computer Club, IT club, Academic Challenge.
                            Grow it.
                        </div>

                    </div>
                    <div className={styles.content_container}>
                        <div className={styles.title_content}>Achievements</div>
                        <div className={styles.subtitle}>Computer Club</div>
                        <div className={styles.subtitle}>President Team Leader   2019
                        </div>
                        <div className={styles.content_info}>Organized the students and brought in new student to introduced them to programming.
                        </div>
                        <div className={styles.content_info}>Arranged a plan to teach students full development a web apps and software.

                        </div>
                        <div className={styles.content_info}>Trained a group of students on the basics and a few advanced programming techniques
                        </div>
                        <div className={styles.content_info}> Discussed as group goals and ability to accurately gauge needs.
                        </div>
                    </div>
                    <div className={styles.content_container}>
                        <div className={styles.subtitle}>Medical Lab</div>
                        <div className={styles.subtitle}>Assistant and Volunteer                                                                                                          Summer, 2018
                        </div>
                        <div className={styles.content_info}>Worked for 240hr as a medical lab assistant at infinity diagnosis labs
                        </div>
                        <div className={styles.content_info}>Worked with blood samples, and the movement and safety of them.

                        </div>
                        <div className={styles.content_info}>Managed ACL TOP 300 from control and maintenance to sample testing
                        </div>
                        <div className={styles.content_info}> Worked with Centaur XP and Advia 1800 for routine Immunoassay testing
                        </div>
                        <div className={styles.content_info}> Maintained a sterile work environment for accurate testing.
                        </div>
                    </div>
                    <div className={styles.content_container}>
                        <div className={styles.title_content}>Skills</div>
                        <div className={styles.content_info}>Proficient in Photoshop and Fusion 360
                        </div>
                        <div className={styles.content_info}>Proficient in Node js and NPM
                        </div>
                        <div className={styles.content_info}>Knowledge of HTML, CSS, and JavaScript
                        </div>
                        <div className={styles.content_info}>Knowledge of Java, C#, and Phyton
                        </div>
                        <div className={styles.content_info}>Ability to use and operate Linux through command line
                        </div>
                        <div className={styles.content_info}>In-depth knowledge of Windows
                        </div>
                        <div className={styles.content_info}>Development of webpages using bootstrap and jQuery
                        </div>
                        <div className={styles.content_info}>Ability to use GitHub, Visual Studio, Visual Studio Code, Putty, Apache, Remote Desktop, PowerShell, VNC, and SSH.
                        </div>
                    </div>
                    <div className={styles.download_button}>
                        <div className={styles.button}>
                            Download Resume PDF
                        </div>
                    </div>
                </div>

            </div>
            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>

                </a>
                <a>
                    Created With{' '}
                    <span className={styles.logo}>
                        <Image src="/Nextjs-logo.svg" alt="Next JS Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    )
}

export default Resume